<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5qB9o9g\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5qB9o9g/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container5qB9o9g.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container5qB9o9g\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container5qB9o9g\App_KernelProdContainer([
    'container.build_hash' => '5qB9o9g',
    'container.build_id' => '15091064',
    'container.build_time' => 1755101777,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5qB9o9g');
