controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

E01Bundle:
    resource: '../src/E01Bundle/Controller'
    type: annotation

E02Bundle:
    resource: '../src/E02Bundle/Controller'
    type: annotation

E03Bundle:
    resource: '../src/E03Bundle/Controller'
    type: annotation

E04Bundle:
    resource: '../src/E04Bundle/Controller'
    type: annotation

E05Bundle:
    resource: '../src/E05Bundle/Controller'
    type: annotation

E06Bundle:
    resource: '../src/E06Bundle/Controller'
    type: annotation

E07Bundle:
    resource: '../src/E07Bundle/Controller'
    type: annotation
