services:
    # Enregistre tous les services (contrôleurs, form, etc.) sauf exclusions
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/**/Entity/'
            - '../src/**/DependencyInjection/'

    # Enregistre TOUS les contrôleurs de TOUS les bundles (E01 à E07)
    App\E01Bundle\Controller\:
        resource: '../src/E01Bundle/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\E02Bundle\Controller\:
        resource: '../src/E02Bundle/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\E03Bundle\Controller\:
        resource: '../src/E03Bundle/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\E04Bundle\Controller\:
        resource: '../src/E04Bundle/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\E05Bundle\Controller\:
        resource: '../src/E05Bundle/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\E06Bundle\Controller\:
        resource: '../src/E06Bundle/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\E07Bundle\Controller\:
        resource: '../src/E07Bundle/Controller'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    App\EventListener\PingDatabaseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 5000 }

    _defaults:
        autowire: true
        autoconfigure: true
