services:
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/EventListener/' # <--- HERE
            - '../src/Kernel.php'   

    App\EventListener\PingDatabaseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 255 }

    _defaults:
        autowire: true
        autoconfigure: true