<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPtx7SxB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPtx7SxB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPtx7SxB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPtx7SxB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPtx7SxB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ptx7SxB',
    'container.build_id' => '329683e6',
    'container.build_time' => 1755101776,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPtx7SxB');
