<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'e01_index' => [[], ['_controller' => 'App\\Controller\\E01Controller::index'], [], [['text', '/e01']], [], [], []],
    'e01_need_auth' => [[], ['_controller' => 'App\\Controller\\E01Controller::need_auth'], [], [['text', '/e01/need_auth']], [], [], []],
    'e01_welcome' => [[], ['_controller' => 'App\\Controller\\E01Controller::welcome'], [], [['text', '/e01/welcome']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/e01/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/e01/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/e01/logout']], [], [], []],
    'App\Controller\E01Controller::index' => [[], ['_controller' => 'App\\Controller\\E01Controller::index'], [], [['text', '/e01']], [], [], []],
    'App\Controller\E01Controller::need_auth' => [[], ['_controller' => 'App\\Controller\\E01Controller::need_auth'], [], [['text', '/e01/need_auth']], [], [], []],
    'App\Controller\E01Controller::welcome' => [[], ['_controller' => 'App\\Controller\\E01Controller::welcome'], [], [['text', '/e01/welcome']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/e01/register']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/e01/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/e01/logout']], [], [], []],
];
