security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserCustomAuthenticator
            # logout: true  # Optionnel, si tu veux utiliser la route /logout de Symfony

    access_control:
        # On laisse vide ou on ajoute au besoin, mais tu gères déjà tout via #[IsGranted]
        # Exemples (inutile ici si tout est dans les controllers) :
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }