<?php

namespace ContainerPtx7SxB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getE02BundleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\E02Controller\Controller\E02Bundle' shared autowired service.
     *
     * @return \App\E02Controller\Controller\E02Bundle
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/E02Controller/Controller/E02Bundle.php';

        $container->services['App\\E02Controller\\Controller\\E02Bundle'] = $instance = new \App\E02Controller\Controller\E02Bundle();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\E02Controller\\Controller\\E02Bundle', $container));

        return $instance;
    }
}
