<?php

namespace Container5qB9o9g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getE01ControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\E01Controller' shared autowired service.
     *
     * @return \App\Controller\E01Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\E01Controller'] = $instance = new \App\Controller\E01Controller();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\E01Controller', $container));

        return $instance;
    }
}
