<?php

namespace Container5qB9o9g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getE02BundleService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\E02Controller\Controller\E02Bundle' shared autowired service.
     *
     * @return \App\E02Controller\Controller\E02Bundle
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\E02Controller\\Controller\\E02Bundle'] = $instance = new \App\E02Controller\Controller\E02Bundle();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\E02Controller\\Controller\\E02Bundle', $container));

        return $instance;
    }
}
